"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { Suspense, useMemo } from "react";
import { decodePayload, type A2uiDeliverable } from "@gloomy/a2ui-spec";
import { A2uiRenderer } from "@/components/A2uiRenderer";

/**
 * Public deliverable viewer: renders a payload encoded directly into the
 * URL (?p=...) - the link a marketplace buyer (OKX ASP) receives when
 * gloomy delivers a task, or a non-web A2MCP caller gets back from
 * `/api/chat`. Stateless: no storage behind it, and the payload is
 * schema-validated by decodePayload before anything renders. Handles both
 * the current OpenUI Lang contract and pre-migration `{component, props}`
 * links - see docs/openui-migration.md.
 */
function DeliverableView() {
  const searchParams = useSearchParams();
  const encoded = searchParams.get("p");

  const result = useMemo<
    { ok: true; payload: A2uiDeliverable } | { ok: false; message: string }
  >(() => {
    if (!encoded) {
      return { ok: false, message: "This link is missing its payload." };
    }
    try {
      return { ok: true, payload: decodePayload(encoded) };
    } catch {
      return {
        ok: false,
        message: "This link's payload is invalid or corrupted.",
      };
    }
  }, [encoded]);

  return (
    <div className="deliverable">
      <p className="deliverable-eyebrow">Generated by gloomy</p>

      {result.ok ? (
        <div className="lv3-stage deliverable-stage">
          <A2uiRenderer deliverable={result.payload} />
        </div>
      ) : (
        <div className="status error">{result.message}</div>
      )}

      <p className="deliverable-footer">
        gloomy turns questions into interactive components.{" "}
        <Link href="/chat">Ask it something yourself</Link>.
      </p>
    </div>
  );
}

export default function DeliverablePage() {
  return (
    <main className="lv3-theme">
      <Suspense fallback={null}>
        <DeliverableView />
      </Suspense>
    </main>
  );
}
